import type { MediaItem, MediaSource } from '../types'

export const sampleSource: MediaSource = {
  id: 'sample-source',
  label: 'Sample geotagged library',
  addedAt: 1_704_067_200_000,
}

const day = 24 * 60 * 60 * 1_000

export const sampleMedia: MediaItem[] = [
  {
    id: 'sample-zurich-limmat',
    sourceId: sampleSource.id,
    relativePath: 'zurich/limmat-evening.jpg',
    displayName: 'Limmat evening',
    kind: 'image',
    mimeType: 'image/jpeg',
    sizeBytes: 4_200_000,
    width: 4000,
    height: 3000,
    capturedAt: Date.UTC(2024, 4, 11, 18, 20),
    capturedAtSource: 'exif',
    latitude: 47.3769,
    longitude: 8.5417,
    geoSource: 'exif',
    lastSeenAt: Date.now(),
  },
  {
    id: 'sample-basel-rhine',
    sourceId: sampleSource.id,
    relativePath: 'basel/rhine-walk.jpg',
    displayName: 'Rhine walk',
    kind: 'image',
    mimeType: 'image/jpeg',
    sizeBytes: 3_600_000,
    width: 3840,
    height: 2160,
    capturedAt: Date.UTC(2023, 8, 2, 10, 5),
    capturedAtSource: 'exif',
    latitude: 47.5596,
    longitude: 7.5886,
    geoSource: 'exif',
    lastSeenAt: Date.now() - day,
  },
  {
    id: 'sample-munich-park',
    sourceId: sampleSource.id,
    relativePath: 'munich/english-garden.jpg',
    displayName: 'English Garden',
    kind: 'image',
    mimeType: 'image/jpeg',
    sizeBytes: 5_100_000,
    width: 4200,
    height: 2800,
    capturedAt: Date.UTC(2022, 6, 20, 14, 45),
    capturedAtSource: 'exif',
    latitude: 48.1582,
    longitude: 11.5878,
    geoSource: 'exif',
    lastSeenAt: Date.now() - 2 * day,
  },
  {
    id: 'sample-venice-canal',
    sourceId: sampleSource.id,
    relativePath: 'venice/canal.mp4',
    displayName: 'Canal clip',
    kind: 'video',
    mimeType: 'video/mp4',
    sizeBytes: 32_000_000,
    durationMs: 42_000,
    capturedAt: Date.UTC(2021, 9, 5, 9, 15),
    capturedAtSource: 'filesystem',
    latitude: 45.4408,
    longitude: 12.3155,
    geoSource: 'manual',
    lastSeenAt: Date.now() - 3 * day,
  },
  {
    id: 'sample-reykjavik-harbor',
    sourceId: sampleSource.id,
    relativePath: 'iceland/reykjavik-harbor.jpg',
    displayName: 'Reykjavik harbor',
    kind: 'image',
    mimeType: 'image/jpeg',
    sizeBytes: 6_400_000,
    width: 4600,
    height: 3000,
    capturedAt: Date.UTC(2020, 1, 12, 16, 0),
    capturedAtSource: 'exif',
    latitude: 64.1466,
    longitude: -21.9426,
    geoSource: 'exif',
    lastSeenAt: Date.now() - 4 * day,
  },
  {
    id: 'sample-no-gps',
    sourceId: sampleSource.id,
    relativePath: 'unsorted/kitchen.jpg',
    displayName: 'Kitchen no GPS',
    kind: 'image',
    mimeType: 'image/jpeg',
    sizeBytes: 2_100_000,
    width: 3000,
    height: 2000,
    capturedAt: Date.UTC(2024, 0, 7, 8, 30),
    capturedAtSource: 'filesystem',
    lastSeenAt: Date.now() - 5 * day,
  },
]

